version: '3'

services:
  webapp:
    build: .
    image: tasukeru_bot_dev
    container_name: "webapp"
    volumes:
      - "./webapp:/webapp"
    ports:
      - 5000:8000
    env_file:
      - ./.env
    # heroku config:setでPORTの環境変数渡したくないので分けて設定
    environment:
      - PORT=8000