version: '3'

services:
  webapp:
    # build: .
    image: tasukeru_bot_dev
    container_name: "webapp"
    volumes:
      - "./webapp:/webapp"
    ports:
      - 5000:8000
    env_file:
      - ./.env
    # command: /bin/sh -c "while :; do sleep 10; done"